name: Build and Deploy Site
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  build-dev:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Write environment variables
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=\"${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=\"${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_URL=\"${{ vars.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=\"${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}\"" >> .env.local
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
  build-stable:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Write environment variables
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=\"${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=\"${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_URL=\"${{ vars.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=\"${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}\"" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=\"${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}\"" >> .env.local
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
permissions:
  contents: write
